### ISSUE TITLE
Automatic translation

### ISSUE THREAD

**Issue by thecodix** [progit/progit2-es#114]
Either you will take into account or not, many of the contributors here are using automated tools like google translate to provide translations, which results in poor quality for understanding books on software development

Please come back to me if you need further proof of this behavior

**Comment by jnavila** [comment]
If it's on ongoing PRs, you can review them. If it's already merged, please open a PR to invalidate the relevant parts. 

@andres-mancera do you need another maintainer on this project ?

**Comment by thecodix** [comment]
Anything by this users: @michaelizer or @ jossue33 at least, I'm 100% sure is copied, since they did the same on a project I'm working on

**Comment by thecodix** [comment]
Could try to point out the issues later

**Comment by jnavila** [comment]
Thanks for raising the issue. I'm not in charge of all the translations, but as you point out, there are some rules to follow.

One cannot simply translate a part of a book without context. In fact, translating a book, even in part is such an endeavour that if you really want to be efficient and produce a good work, you must have at least read it all, made notes of terms and used Git so that you know where you stand when translating each paragraph.

**Comment by andres-mancera** [comment]
Thanks for your feedback @thecodix .  As you would understand, I don't have the bandwidth to go over each and every pull request that is made.  I always perform a quick "spot check" and then either accept and/or make comments to the individual.  Since there are a few translators that have been already reported, I'll make sure I check their work going forward.  

Hey @jnavila : I'll think I should be able to handle the Spanish translation (the way I have been doing it so far).  To be honest, the project has not been very active (with the exception of the last 3~4 weeks, where I've gotten a burst of pull requests by different folks).

**Comment by jnavila** [comment]
@andres-mancera As said in #112 , if I can set up the automatic compilation of the book, you can take advantage of some automatic checks of style, internal links and overall compilation of the book (that's what it's made for).

**Comment by andres-mancera** [comment]
@jnavila Yes, I saw that and was planning to ping you as soon as this burst of pull requests is over, i.e., when the repository is somewhat idle.  I'll definitely get in touch with you soon so that you can help me set up the automatic publishing.  Cheers.
